songs/melody/artist/urls.py
from . import views
from django.urls import path
app_name='artist'
urlpatterns = [
    path('',views.tracks,name='tracks'),
    path('songs/<int:song_id>/',views.details,name='details'),
    path('add/',views.add,name='add'),
    path('update/<int:id>/',views.update,name='update'),
    path('delete/<int:id>/',views.delete,name='delete')
]

songs/melody/melody/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('artist.urls'))
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                         document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

songs/melody/artist/models.py
from django.db import models

# Create your models here.
class Songs(models.Model):
    name=models.CharField(max_length=250)
    artist=models.TextField()
    year=models.IntegerField()
    image=models.ImageField(upload_to='gallery')

    def __str__(self):
        return self.name

songs/melody/artist/forms.py
from django import forms
from . models import Songs

class SongForm(forms.ModelForm):
    class Meta:
        model=Songs
        fields=('name','artist','year','image')

songs/melody/artist/views.py
from django.http import HttpResponse
from django.shortcuts import render, redirect

from artist.forms import SongForm
from artist.models import Songs



def tracks(request):
    songs=Songs.objects.all()
    content={'song_list':songs}
    return render(request,'index.html',content)

def details(request, song_id):
    songs=Songs.objects.get(id=song_id)
    return  render(request,'details.html',{'songs':songs})

def add(request):
    if request.method == "POST":
        name=request.POST.get('name',)
        artist=request.POST.get('artist',)
        year=request.POST.get('year',)
        image=request.FILES['image']
        song=Songs(name=name,artist=artist,year=year,image=image)
        song.save()
        return redirect('/')
    return render(request,'add.html')

def update(request,id):
    song=Songs.objects.get(id=id)
    form=SongForm(request.POST or None,request.FILES, instance=song)
    if form.is_valid():
        form.save()
        return redirect('/')
    return render(request,'edit.html',{'form':form,'song':song})

def delete(request,id):
    if request.method=="POST":
        song=Songs.objects.get(id=id)
        song.delete()
        return redirect('/')
    return render(request,'delete.html')

songs/melody/templates/add.html
{% extends 'base.html'%}
{% block body %}
<form style="padding:25px" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <p><b>ADD DETAILS</b></p>
    <input type="text" name="name" placeholder="enter song name"><br><br>
    <input type="text" name="artist" placeholder="enter artist detail"><br><br>
    <input type="number" name="year" placeholder="enter year"><br><br>
    <input type="file" name="image"><br><br>
    <input type="submit">
</form>
{% endblock %}

songs/melody/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
<!--    <link rel="stylesheet" href="{% static 'style.css' %}">-->
</head>
<body style="background: linear-gradient(90deg, #FC466B 0%, #3F5EFB 100%);">
<!-- Image and text -->
<nav class="navbar navbar-light bg-dark">
  <a style="color:white" class="navbar-brand" href="#">
        Online Song Information
  </a>
</nav>
{% block body %}
{% endblock %}
</body>
</html>

songs/melody/templates/delete.html
{% extends 'base.html' %}
{% block body %}
<form style="padding:25px" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <b>Are you sure to delete the informations ?</b><br><br>
    <input type="submit">
</form>
{% endblock %}

songs/melody/templates/details.html
{% extends 'base.html' %}
{% block body %}

<div  class="container">
    <div class="row">
        <div style="padding:25px" class="col-md-6">
        <img src="{{songs.image.url}}" width="300" height="300">
        </div>

        <div style="padding:25px" class="col-md-6">
          <h3>{{songs.name}}</h3>
          <h4>{{songs.artist}}</h4>
          <h6>{{songs.year}}</h6>

           <a class="btn btn-warning" href="{% url 'artist:update' songs.id %}">update</a> &nbsp;
           <a class="btn btn-danger" href="{% url 'artist:delete' songs.id %}">delete</a>
        </div>
    </div>
</div>

{% endblock %}

songs/melody/templates/edit.html
{% extends 'base.html' %}
{% block body %}
<form style="padding:25px" method='post' enctype="multipart/form-data">
    {% csrf_token %}
    <h3>UPDATE</h3>
     {{form.as_p}}
<input type="submit">
</form>
{% endblock %}

songs/melody/templates/index.html
{% extends 'base.html' %}
{% block body %}

<div class="container">
    <div class="row">
        {% for i in song_list %}

        <div style="padding:25px" class="col-md-3">
            <div class="card">
  <img class="card-img-top" src="{{i.image.url}}" alt="Card image cap" width="200" height="250">
  <div class="card-body">
    <h5 class="card-title">{{i.name}}</h5>
    <p class="card-text">{{i.artist}}</p>
    <a href="{% url 'artist:details' i.id %}" class="btn btn-primary">View Details</a> <br>


  </div>
</div>
        </div>
        {% endfor %}
    </div>
    <a href="{% url 'artist:add'  %}" class="btn btn-primary">Add New Song  </a>
</div>

{% endblock %}